selenoid:
  listen: ":4444"
  ggr-host: ""
  disable-docker: false
  disable-queue: false
  enable-file-upload: false
  browsers-config: "config/browsers.json"
  log-conf: "config/container-logs.json"
  retry-count: 1
  timeout: 60
  max-timeout: 1
  session-attempt-timeout: 30
  session-delete-timeout: 30
  service-startup-timeout: 30
  limit-auto: true
  cpu: 1
  mem: 512
  container-network: "default"
  capture-driver-logs: false
  disable-privileged: false
  video-output-dir: "video"
  video-recorder-image: "selenoid/video-recorder:latest-release"
  log-output-dir: ""
  save-all-logs: false
  graceful-period: 300